export let apps = [
  {app: "Exchange", app_id: "exchange"},
  {app: "Supply Tool", app_id: "supplyTool"}
]

export let reports = [
  {app_id: "exchange", report: "Reports -> Report Builder", report_id: "reportBuilder", url: "https://exchange.loopme.com/app/reports"}
]

const use_events_with_requests_cube = "usage of this column forces backend to use events_with_requests cube";

export let columns = [
// based on https://github.com/loopme/angular-webjars/blob/master/apps/exchange-tool/src/app/reports/definitions/const/reports-metrics.const.ts
  {report_id: "reportBuilder", column: "Requests", column_id: "requests", type: "metric", comment: use_events_with_requests_cube},
  {report_id: "reportBuilder", column: "Bids", column_id: "bids", type: "metric"},
  {report_id: "reportBuilder", column: "Bid rate, %", column_id: "bidRate", type: "metric"},
  {report_id: "reportBuilder", column: "Display rate, %", column_id: "displayRate", type: "metric"},
  {report_id: "reportBuilder", column: "Impressions", column_id: "impressions", type: "metric"},
  {report_id: "reportBuilder", column: "Video Completes", column_id: "videoCompletes", type: "metric"},
  {report_id: "reportBuilder", column: "VCR, %", column_id: "vcr", type: "metric"},
  {report_id: "reportBuilder", column: "Clicks", column_id: "adClicks", type: "metric"},
  {report_id: "reportBuilder", column: "CTR, %", column_id: "ctr", type: "metric"},
  {report_id: "reportBuilder", column: "Spend, $", column_id: "spends", type: "metric"},
  {report_id: "reportBuilder", column: "CPM, $", column_id: "avgCpm", type: "metric"},
  {report_id: "reportBuilder", column: "rCPM, $", column_id: "rCpm", type: "metric", comment: use_events_with_requests_cube},
  {report_id: "reportBuilder", column: "Media cost, $", column_id: "deliveredDollars", type: "metric"},
  {report_id: "reportBuilder", column: "Alt bids", column_id: "altResponses", type: "metric"},
  {report_id: "reportBuilder", column: "No bids", column_id: "noAds", type: "metric", comment: use_events_with_requests_cube},
  {report_id: "reportBuilder", column: "Media CPM, $", column_id: "mediaCpm", type: "metric"},
  {report_id: "reportBuilder", column: "DSP Fee, $", column_id: "dspFee", type: "metric"},
// based on apps/exchange-tool/src/app/reports/definitions/const/reports-dimensions.const.ts
// and      apps/exchange-tool/src/app/reports/definitions/const/reports-table-preset.const.ts
  {report_id: "reportBuilder", column: "Country", column_id: "country", type: "dimension"},
  {report_id: "reportBuilder", column: "Date", column_id: "date", type: "dimension"},
  {report_id: "reportBuilder", column: "Deal", column_id: "deal", type: "dimension"},
  {report_id: "reportBuilder", column: "DSP", column_id: "dspAccountName", type: "dimension"},
  {report_id: "reportBuilder", column: "Dsp ID", column_id: "dspAccountId", type: "dimension"},
  {report_id: "reportBuilder", column: "Endpoint", column_id: "endpointName", type: "dimension"},
  {report_id: "reportBuilder", column: "Endpoint ID", column_id: "endpointId", type: "dimension"},
  {report_id: "reportBuilder", column: "Platform", column_id: "platformName", type: "dimension"},
  {report_id: "reportBuilder", column: "LineItem Name", column_id: "lineItemName", type: "dimension"},
  {report_id: "reportBuilder", column: "Publisher Name", column_id: "publisherName", type: "dimension"},
  {report_id: "reportBuilder", column: "Publisher ID", column_id: "publisherId", type: "dimension"},
  {report_id: "reportBuilder", column: "Bundle ID/Site Domain", column_id: "marketUrl", type: "dimension"},
  {report_id: "reportBuilder", column: "Impression Type", column_id: "adFormat", type: "dimension"},
  {report_id: "reportBuilder", column: "Ad Size", column_id: "size", type: "dimension"},
  {report_id: "reportBuilder", column: "Advertiser Domain", column_id: "advertiserDomain", type: "dimension"},
  {report_id: "reportBuilder", column: "Device Types", column_id: "deviceType", type: "dimension"},
  {report_id: "reportBuilder", column: "DSP Ad Sales Lead", column_id: "dspAdSalesLeadName", type: "dimension"},
  {report_id: "reportBuilder", column: "DSP Account Manager", column_id: "dspAccountManagerName", type: "dimension"},
  {report_id: "reportBuilder", column: "Deal Ad Sales Lead", column_id: "dealAdSalesLeadName", type: "dimension"},
  {report_id: "reportBuilder", column: "Deal Campaign Manager", column_id: "dealCampaignManagerName", type: "dimension"},
].map( col => {
  col.reportColumn = col.report_id + '.' + col.column_id;
  return col;
})

export let cubes = [
  {cube_id: "events", factTable: "stats.exchange_stats_daily_dist", granularity: ["hourly", "daily", "monthly"]},
  {cube_id: "events_with_requests", factTable: "stats.exchange_requests_stats_dist", granularity: ["hourly", "daily"]},
]

export let fields = [
  {cube_id: "events", field_id: "bids", type: "metric"},
  {cube_id: "events", field_id: "wins", type: "metric"},
  {cube_id: "events", field_id: "impressions", type: "metric"},
  {cube_id: "events", field_id: "video_completes", type: "metric"},
  {cube_id: "events", field_id: "ad_clicks", type: "metric"},
  {cube_id: "events", field_id: "spends", type: "metric"},
  {cube_id: "events", field_id: "delivered_dollars", type: "metric"},
  {cube_id: "events", field_id: "display_rate", type: "metric"},
  {cube_id: "events", field_id: "ctr", type: "metric"},
  {cube_id: "events", field_id: "vcr", type: "metric"},
  {cube_id: "events", field_id: "profit_margin", type: "metric"},
  {cube_id: "events", field_id: "media_cpm", type: "metric"},
  {cube_id: "events", field_id: "avg_cpm", type: "metric"},
  {cube_id: "events", field_id: "dsp_fee", type: "metric"},
  {cube_id: "events", field_id: "burl", type: "metric"},
  {cube_id: "events", field_id: "redirects", type: "metric"},
  {cube_id: "events", field_id: "failed_redirects", type: "metric"},
  {cube_id: "events", field_id: "failed_redirect_imps", type: "metric"},
  {cube_id: "events", field_id: "failed_redirect_burls", type: "metric"},
  {cube_id: "events", field_id: "failed_redirect_wins", type: "metric"},

  {cube_id: "events", field_id: "country", type: "dimension"},
  {cube_id: "events", field_id: "endpoint_id", type: "dimension"},
  {cube_id: "events", field_id: "endpoint_name", type: "dimension"},
  {cube_id: "events", field_id: "endpoint_aggregator_group", type: "dimension"},
  {cube_id: "events", field_id: "dsp_id", type: "dimension"},
  {cube_id: "events", field_id: "dsp_name", type: "dimension"},
  {cube_id: "events", field_id: "dsp_account_id", type: "dimension"},
  {cube_id: "events", field_id: "dsp_account_name", type: "dimension"},
  {cube_id: "events", field_id: "dsp_ad_sales_lead_name", type: "dimension"},
  {cube_id: "events", field_id: "dsp_account_manager_name", type: "dimension"},
  {cube_id: "events", field_id: "deal_ad_sales_lead_name", type: "dimension"},
  {cube_id: "events", field_id: "deal_account_manager_name", type: "dimension"},
  {cube_id: "events", field_id: "deal_campaign_manager_name", type: "dimension"},
  {cube_id: "events", field_id: "deal_id", type: "dimension"},
  {cube_id: "events", field_id: "deal_token", type: "dimension"},
  {cube_id: "events", field_id: "deal_name", type: "dimension"},
  {cube_id: "events", field_id: "account_id", type: "dimension"},
  {cube_id: "events", field_id: "deal_organization_id", type: "dimension"},
  {cube_id: "events", field_id: "always_on_deal", type: "dimension"},
  {cube_id: "events", field_id: "organization_id", type: "dimension"},
  {cube_id: "events", field_id: "line_item_name", type: "dimension"},
  {cube_id: "events", field_id: "line_item_id", type: "dimension"},
  {cube_id: "events", field_id: "deal_line_item_id", type: "dimension"},
  {cube_id: "events", field_id: "size", type: "dimension"},
  {cube_id: "events", field_id: "publisher_id", type: "dimension"},
  {cube_id: "events", field_id: "publisher_name", type: "dimension"},
  {cube_id: "events", field_id: "ad_format", type: "dimension"},
  {cube_id: "events", field_id: "advertiser_domain", type: "dimension"},
  {cube_id: "events", field_id: "adomain_to_iab_mapping_id", type: "dimension"},
  {cube_id: "events", field_id: "advertiser_domain_allowed", type: "dimension"},
  {cube_id: "events", field_id: "platform_id", type: "dimension"},
  {cube_id: "events", field_id: "bundle_platform_id", type: "dimension"},
  {cube_id: "events", field_id: "platform_name", type: "dimension"},
  {cube_id: "events", field_id: "market_url", type: "dimension"},
  {cube_id: "events", field_id: "bundle_id", type: "dimension"},
  {cube_id: "events", field_id: "bundle_name", type: "dimension"},
  {cube_id: "events", field_id: "device_type", type: "dimension"},
  {cube_id: "events", field_id: "interstitial", type: "dimension"},
  {cube_id: "events", field_id: "creative_id", type: "dimension"},
  {cube_id: "events", field_id: "campaign_id", type: "dimension"},
  {cube_id: "events", field_id: "seat_id", type: "dimension"},

  {cube_id: "events_with_requests", field_id: "requests", type: "metric"},
  {cube_id: "events_with_requests", field_id: "tmax_lim_requests", type: "metric"},
  {cube_id: "events_with_requests", field_id: "available_requests", type: "metric"},
  {cube_id: "events_with_requests", field_id: "bids", type: "metric"},
  {cube_id: "events_with_requests", field_id: "wins", type: "metric"},
  {cube_id: "events_with_requests", field_id: "available", type: "metric"},
  {cube_id: "events_with_requests", field_id: "no_ads", type: "metric"},
  {cube_id: "events_with_requests", field_id: "impressions", type: "metric"},
  {cube_id: "events_with_requests", field_id: "video_completes", type: "metric"},
  {cube_id: "events_with_requests", field_id: "ad_clicks", type: "metric"},
  {cube_id: "events_with_requests", field_id: "timeouts", type: "metric"},
  {cube_id: "events_with_requests", field_id: "errors", type: "metric"},
  {cube_id: "events_with_requests", field_id: "redirects", type: "metric"},
  {cube_id: "events_with_requests", field_id: "failed_redirects", type: "metric"},
  {cube_id: "events_with_requests", field_id: "failed_redirect_imps", type: "metric"},
  {cube_id: "events_with_requests", field_id: "failed_redirect_burls", type: "metric"},
  {cube_id: "events_with_requests", field_id: "failed_redirect_wins", type: "metric"},
  {cube_id: "events_with_requests", field_id: "alt_responses", type: "metric"},
  {cube_id: "events_with_requests", field_id: "spends", type: "metric"},
  {cube_id: "events_with_requests", field_id: "delivered_dollars", type: "metric"},
  {cube_id: "events_with_requests", field_id: "timeouts_rate", type: "metric"},
  {cube_id: "events_with_requests", field_id: "error_rate", type: "metric"},
  {cube_id: "events_with_requests", field_id: "bid_rate", type: "metric"},
  {cube_id: "events_with_requests", field_id: "wins_rate", type: "metric"},
  {cube_id: "events_with_requests", field_id: "display_rate", type: "metric"},
  {cube_id: "events_with_requests", field_id: "ctr", type: "metric"},
  {cube_id: "events_with_requests", field_id: "vcr", type: "metric"},
  {cube_id: "events_with_requests", field_id: "profit_margin", type: "metric"},
  {cube_id: "events_with_requests", field_id: "media_cpm", type: "metric"},
  {cube_id: "events_with_requests", field_id: "avg_cpm", type: "metric"},
  {cube_id: "events_with_requests", field_id: "r_cpm", type: "metric"},
  {cube_id: "events_with_requests", field_id: "dsp_fee", type: "metric"},
  {cube_id: "events_with_requests", field_id: "avg_throttle_rate", type: "metric"},
  {cube_id: "events_with_requests", field_id: "avg_response_time", type: "metric"},
  {cube_id: "events_with_requests", field_id: "adv_spends", type: "metric"},
  {cube_id: "events_with_requests", field_id: "adv_cpm", type: "metric"},
  {cube_id: "events_with_requests", field_id: "burl", type: "metric"},
  {cube_id: "events_with_requests", field_id: "pub_spends", type: "metric"},
  {cube_id: "events_with_requests", field_id: "pub_cpm", type: "metric"},

  {cube_id: "events_with_requests", field_id: "country", type: "dimension"},
  {cube_id: "events_with_requests", field_id: "endpoint_id", type: "dimension"},
  {cube_id: "events_with_requests", field_id: "endpoint_name", type: "dimension"},
  {cube_id: "events_with_requests", field_id: "endpoint_aggregator_group", type: "dimension"},
  {cube_id: "events_with_requests", field_id: "dsp_id", type: "dimension"},
  {cube_id: "events_with_requests", field_id: "dsp_name", type: "dimension"},
  {cube_id: "events_with_requests", field_id: "dsp_account_id", type: "dimension"},
  {cube_id: "events_with_requests", field_id: "dsp_account_name", type: "dimension"},
  {cube_id: "events_with_requests", field_id: "dsp_ad_sales_lead_name", type: "dimension"},
  {cube_id: "events_with_requests", field_id: "dsp_account_manager_name", type: "dimension"},
  {cube_id: "events_with_requests", field_id: "deal_ad_sales_lead_name", type: "dimension"},
  {cube_id: "events_with_requests", field_id: "deal_account_manager_name", type: "dimension"},
  {cube_id: "events_with_requests", field_id: "deal_campaign_manager_name", type: "dimension"},
  {cube_id: "events_with_requests", field_id: "deal_id", type: "dimension"},
  {cube_id: "events_with_requests", field_id: "deal_token", type: "dimension"},
  {cube_id: "events_with_requests", field_id: "deal_name", type: "dimension"},
  {cube_id: "events_with_requests", field_id: "account_id", type: "dimension"},
  {cube_id: "events_with_requests", field_id: "deal_organization_id", type: "dimension"},
  {cube_id: "events_with_requests", field_id: "always_on_deal", type: "dimension"},
  {cube_id: "events_with_requests", field_id: "organization_id", type: "dimension"},
  {cube_id: "events_with_requests", field_id: "line_item_name", type: "dimension"},
  {cube_id: "events_with_requests", field_id: "line_item_id", type: "dimension"},
  {cube_id: "events_with_requests", field_id: "deal_line_item_id", type: "dimension"},
  {cube_id: "events_with_requests", field_id: "size", type: "dimension"},
  {cube_id: "events_with_requests", field_id: "publisher_id", type: "dimension"},
  {cube_id: "events_with_requests", field_id: "publisher_name", type: "dimension"},
  {cube_id: "events_with_requests", field_id: "ad_format", type: "dimension"},
  {cube_id: "events_with_requests", field_id: "advertiser_domain", type: "dimension"},
  {cube_id: "events_with_requests", field_id: "adomain_to_iab_mapping_id", type: "dimension"},
  {cube_id: "events_with_requests", field_id: "advertiser_domain_allowed", type: "dimension"},
  {cube_id: "events_with_requests", field_id: "platform_id", type: "dimension"},
  {cube_id: "events_with_requests", field_id: "bundle_platform_id", type: "dimension"},
  {cube_id: "events_with_requests", field_id: "platform_name", type: "dimension"},
  {cube_id: "events_with_requests", field_id: "market_url", type: "dimension"},
  {cube_id: "events_with_requests", field_id: "bundle_id", type: "dimension"},
  {cube_id: "events_with_requests", field_id: "bundle_name", type: "dimension"},
  {cube_id: "events_with_requests", field_id: "device_type", type: "dimension"},
  {cube_id: "events_with_requests", field_id: "interstitial", type: "dimension"},
  {cube_id: "events_with_requests", field_id: "creative_id", type: "dimension"},
  {cube_id: "events_with_requests", field_id: "campaign_id", type: "dimension"},
  {cube_id: "events_with_requests", field_id: "seat_id", type: "dimension"},
].map(field => {
  field.cubeField = field.cube_id + '.' + field.field_id;
  return field;
})

export let column2field = [
  {reportColumn: "reportBuilder.requests", cubeField: "events_with_requests.requests"},
  {reportColumn: "reportBuilder.bids", cubeField: "events_with_requests.bids"},
  {reportColumn: "reportBuilder.bids", cubeField: "events.bids"},
  {reportColumn: "reportBuilder.bidRate", cubeField: "events_with_requests.bid_rate"},
  {reportColumn: "reportBuilder.displayRate", cubeField: "events_with_requests.display_rate"},
  {reportColumn: "reportBuilder.displayRate", cubeField: "events.display_rate"},
  {reportColumn: "reportBuilder.impressions", cubeField: "events_with_requests.impressions"},
  {reportColumn: "reportBuilder.impressions", cubeField: "events.impressions"},
  {reportColumn: "reportBuilder.vcr", cubeField: "events_with_requests.vcr"},
  {reportColumn: "reportBuilder.vcr", cubeField: "events.vcr"},
  {column: "reportBuilder.ctr", cubeField: "events.ctr"},
  {column: "reportBuilder.spends", cubeField: "events.spends"},
  {column: "reportBuilder.avgCpm", cubeField: "replaceme"},
  {column: "reportBuilder.rCpm", cubeField: "replaceme"},
  {column: "reportBuilder.deliveredDollars", cubeField: "replaceme"},
  {column: "reportBuilder.altResponses", cubeField: "replaceme"},
  {column: "reportBuilder.noAds", cubeField: "replaceme"},
  {column: "reportBuilder.mediaCpm", cubeField: "replaceme"},
  {column: "reportBuilder.dspFee", cubeField: "replaceme"},

  {column: "reportBuilder.country", cubeField: "replaceme"},
  {column: "reportBuilder.date", cubeField: "replaceme"},
  {column: "reportBuilder.deal", cubeField: "replaceme"},
  {column: "reportBuilder.dspAccountName", cubeField: "replaceme"},
  {column: "reportBuilder.dspAccountId", cubeField: "replaceme"},
  {column: "reportBuilder.endpointName", cubeField: "replaceme"},
  {column: "reportBuilder.endpointId", cubeField: "replaceme"},
  {column: "reportBuilder.platformName", cubeField: "replaceme"},
  {column: "reportBuilder.lineItemName", cubeField: "replaceme"},
  {column: "reportBuilder.publisherName", cubeField: "replaceme"},
  {column: "reportBuilder.publisherId", cubeField: "replaceme"},
  {column: "reportBuilder.marketUrl", cubeField: "replaceme"},
  {column: "reportBuilder.adFormat", cubeField: "replaceme"},
  {column: "reportBuilder.size", cubeField: "replaceme"},
  {column: "reportBuilder.advertiserDomain", cubeField: "replaceme"},
  {column: "reportBuilder.deviceType", cubeField: "replaceme"},
  {column: "reportBuilder.dspAdSalesLeadName", cubeField: "replaceme"},
  {column: "reportBuilder.dspAccountManagerName", cubeField: "replaceme"},
  {column: "reportBuilder.dealAdSalesLeadName", cubeField: "replaceme"},
  {column: "reportBuilder.dealCampaignManagerName", cubeField: "replaceme"},
]